'use strict';
const ARTSHOP=[
 {id:'rune1',name:'Руна мощи I',icon:'⚔️',price:60,desc:'+20% урона',apply:g=>g.stats.dmg+=.2},
 {id:'rune2',name:'Руна мощи II',icon:'⚔️',price:90,req:'rune1',desc:'+35% урона',apply:g=>g.stats.dmg+=.35},
 {id:'rune3',name:'Руна мощи III',icon:'⚔️',price:150,req:'rune2',desc:'+55% урона',apply:g=>g.stats.dmg+=.55},
 {id:'chrono1',name:'Часы мага I',icon:'⏳',price:60,desc:'−10% КД',apply:g=>g.stats.cdr=Math.max(.4,g.stats.cdr*.9)},
 {id:'chrono2',name:'Часы мага II',icon:'⏳',price:95,req:'chrono1',desc:'−18% КД',apply:g=>g.stats.cdr=Math.max(.4,g.stats.cdr*.82)},
 {id:'chrono3',name:'Часы мага III',icon:'⏳',price:150,req:'chrono2',desc:'−26% КД',apply:g=>g.stats.cdr=Math.max(.4,g.stats.cdr*.74)},
 {id:'boots1',name:'Сапоги ветра I',icon:'👢',price:50,desc:'+10% скорость',apply:g=>g.stats.spdMul+=.1},
 {id:'boots2',name:'Сапоги ветра II',icon:'👢',price:85,req:'boots1',desc:'+18% скорость',apply:g=>g.stats.spdMul+=.18},
 {id:'amulet1',name:'Амулет жизни I',icon:'❤️',price:55,keep:true,desc:'+25 макс.HP',apply:g=>{g.player.maxhp+=25;g.player.hp=Math.min(g.player.maxhp,g.player.hp+25);}},
 {id:'amulet2',name:'Амулет жизни II',icon:'❤️',price:95,req:'amulet1',keep:true,desc:'+50 макс.HP',apply:g=>{g.player.maxhp+=50;g.player.hp=Math.min(g.player.maxhp,g.player.hp+50);}},
 {id:'lens1',name:'Фокус-линза I',icon:'🌐',price:60,desc:'+12% область',apply:g=>g.stats.area+=.12},
 {id:'lens2',name:'Фокус-линза II',icon:'🌐',price:100,req:'lens1',desc:'+25% область',apply:g=>g.stats.area+=.25},
 {id:'grim1',name:'Гримуар I',icon:'📖',price:65,desc:'+20% опыт/золото',apply:g=>{g.stats.xp+=.2;g.stats.gold+=.2;}},
 {id:'grim2',name:'Гримуар II',icon:'📖',price:110,req:'grim1',desc:'+40% опыт/золото',apply:g=>{g.stats.xp+=.4;g.stats.gold+=.4;}},
 {id:'vamp',name:'Клык вампира',icon:'🦷',price:110,desc:'+2 HP/убийство',apply:g=>g.stats.vamp+=2},
 {id:'stone',name:'Каменный щит',icon:'🛡️',price:90,desc:'+3 броня',apply:g=>g.stats.armor+=3},
 {id:'phoenix',name:'Перо феникса',icon:'🪶',price:150,desc:'Воскрешение 1 раз',apply:g=>g.stats.phoenix++},
 {id:'crit',name:'Око криты',icon:'👁️',price:100,desc:'каждый 4-й ×2',apply:g=>g.stats.crit=true},
 {id:'stormgem',name:'Гроза-камень',icon:'🌩️',price:130,desc:'авто-молния /6с',apply:g=>g.stats.stormgem=true},
 {id:'prism',name:'Гранёная призма',icon:'🔻',price:120,desc:'+1 луч',apply:g=>g.stats.raysBonus++},
 {id:'mirrorg',name:'Зеркало душ',icon:'🪞',price:120,desc:'+1 двойник',apply:g=>g.stats.mirrorBonus++},
 {id:'tentacles',name:'Щупальца пустоты',icon:'🐙',price:130,desc:'+6% урона за луч',apply:g=>g.stats.tentacles=true},
 {id:'blackcat',name:'Чёрная кошка',icon:'🐈',price:100,desc:'−9% КД',apply:g=>g.stats.cdr=Math.max(.4,g.stats.cdr*.91)},
 {id:'accelerator',name:'Ускоритель',icon:'🏎️',price:110,desc:'КД от скорости',apply:g=>g.stats.accelerator=true},
 {id:'genome',name:'Генофаг',icon:'🧬',price:140,desc:'враги −15% HP',apply:g=>g.stats.genome=true},
 {id:'scythe',name:'Коса жнеца',icon:'🪓',price:140,desc:'8% казнь',apply:g=>g.stats.scythe=true},
 {id:'clockwork',name:'Хронометр',icon:'⏱️',price:130,desc:'стоп-время /20с',apply:g=>g.stats.clockwork=true},
 {id:'amplifier',name:'Усилитель',icon:'📡',price:100,desc:'+20% область',apply:g=>g.stats.area+=.2},
 {id:'electromag',name:'Электромагнит',icon:'🧲',price:120,desc:'+40% вихри/двойники',apply:g=>g.stats.electro=true},
 {id:'ember',name:'Тлеющий уголь',icon:'🔥',price:100,cls:'pyro',desc:'+50% поджог',apply:g=>g.stats.burnMult+=.5},
 {id:'lantern',name:'Фонарь душ',icon:'🏮',price:100,cls:'necro',desc:'+1 скелет',apply:g=>g.stats.skelBonus++},
 {id:'conductor',name:'Проводник',icon:'🔱',price:100,cls:'storm',desc:'+1 цепь',apply:g=>g.stats.chainBonus++},
 {id:'prismc',name:'Призма Архимага',icon:'🔷',price:100,cls:'arcane',desc:'+1 стрела',apply:g=>g.stats.projBonus++},
 {id:'heartflame',name:'Сердце пламени',icon:'*',price:0,craftOnly:true,desc:'+60% поджог,+20% урон',apply:g=>{g.stats.burnMult+=.6;g.stats.dmg+=.2;}},
 {id:'soulvessel',name:'Сосуд душ',icon:'†',price:0,craftOnly:true,desc:'+2 вамп,+1 скелет',apply:g=>{g.stats.vamp+=2;g.stats.skelBonus++;}},
 {id:'stormcore',name:'Ядро бури',icon:'z',price:0,craftOnly:true,desc:'+2 цепи,−10% КД',apply:g=>{g.stats.chainBonus+=2;g.stats.cdr=Math.max(.4,g.stats.cdr*.9);}},
 {id:'focusprism',name:'Фокус-призма',icon:'✦',price:0,craftOnly:true,desc:'+1 стрела,+15% область',apply:g=>{g.stats.projBonus++;g.stats.area+=.15;}},
 {id:'paradox',name:'Парадокс времени',icon:'8',price:0,craftOnly:true,desc:'−20% КД + скорость',apply:g=>{g.stats.cdr=Math.max(.4,g.stats.cdr*.8);g.stats.accelerator=true;}},
 {id:'collector',name:'Око собирателя',icon:'$',price:0,craftOnly:true,desc:'+30% экон,+15% область',apply:g=>{g.stats.xp+=.3;g.stats.gold+=.3;g.stats.area+=.15;}},
 {id:'conqcrown',name:'Корона завоевателя',icon:'&',price:0,craftOnly:true,desc:'+25% урон,крит',apply:g=>{g.stats.dmg+=.25;g.stats.crit=true;}},
 {id:'stormheart',name:'Сердце бури',icon:'≡',price:0,craftOnly:true,desc:'+2 цепи,+40% вихри',apply:g=>{g.stats.chainBonus+=2;g.stats.electro=true;}},
 {id:'infinity',name:'Перчатка бесконечности',icon:'8',price:0,craftOnly:true,desc:'+1 луч,+10%/луч',apply:g=>{g.stats.raysBonus++;g.stats.tentacles=true;g.stats.tentaclesStrong=true;}}];
const RECIPES=[
 {id:'paradox',name:'Парадокс времени',icon:'8',need:['blackcat','accelerator']},
 {id:'collector',name:'Око собирателя',icon:'$',need:['grim1','lens1']},
 {id:'conqcrown',name:'Корона завоевателя',icon:'&',need:['rune2','crit']},
 {id:'stormheart',name:'Сердце бури',icon:'≡',need:['conductor','electromag']},
 {id:'infinity',name:'Перчатка бесконечности',icon:'8',need:['tentacles','prism']},
 {id:'heartflame',name:'Сердце пламени',icon:'*',need:['ember','rune2']},
 {id:'soulvessel',name:'Сосуд душ',icon:'†',need:['lantern','vamp']},
 {id:'stormcore',name:'Ядро бури',icon:'z',need:['conductor','chrono2']},
 {id:'focusprism',name:'Фокус-призма',icon:'✦',need:['prismc','lens2']}];