'use strict';
/* ===== combos-data.js: эволюции и синергии (данные) ===== */
const COMBOS=[
 {id:'sunstorm',name:'Солнечная буря',icon:'🌞',cls:'pyro',
  need:[{id:'fireball',lv:4},{id:'ring',lv:3}],
  desc:'Огненный шар IV + Кольцо магмы III. Потоки огненных шаров и обжигающие новы вокруг вас.'},
 {id:'soulreaper',name:'Жнец душ',icon:'⚰️',cls:'necro',
  need:[{id:'soularrow',lv:4},{id:'deathburst',lv:3}],
  desc:'Стрела души IV + Взрыв душ III. Косы душ пронзают толпы, обрушивая некротические новы.'},
 {id:'skywrath',name:'Гнев небес',icon:'🌌',cls:'storm',
  need:[{id:'lightning',lv:4},{id:'storm',lv:3}],
  desc:'Цепная молния IV + Гроза III. Непрерывные цепные разряды и гром с небес.'},
 {id:'vortex',name:'Великий вихрь',icon:'🌀',cls:'storm',
  need:[{id:'cyclone',lv:4},{id:'ball',lv:3}],
  desc:'Смерч IV + Шаровая молния III. Четыре огромных вихря кружат вокруг вас, затягивая и перемалывая врагов.'},
 {id:'singularity',name:'Сингулярность',icon:'🕳️',cls:'arcane',
  need:[{id:'arcane',lv:4},{id:'nova',lv:3}],
  desc:'Чародейские стрелы IV + Кольцо новы III. Чёрная дыра затягивает врагов и перемалывает их.'},
 {id:'icestorm',name:'Ледяной шторм',icon:'🌨️',cls:'arcane',
  need:[{id:'icelance',lv:4},{id:'ball',lv:3}],
  desc:'Ледяное копьё IV + Шаровая молния III. Град замедляющих осколков и сферы стужи.'},
 {id:'laserstorm',name:'Лазерный шторм',icon:'🌟',cls:'arcane',
  need:[{id:'ray',lv:4},{id:'mirror',lv:3}],
  desc:'Лучи хаоса IV + Двойники III. Все лучи сливаются в один гигантский луч, рассекающий всё на экране.'},
 {id:'avatar',name:'Аватар',icon:'🎭',cls:'arcane',
  need:[{id:'mirror',lv:4},{id:'arcane',lv:3}],
  desc:'Двойники IV + Чародейские стрелы III. Четыре миража синхронно расстреливают врагов усиленными болтами.'},
 {id:'blackdeath',name:'Чёрная смерть',icon:'🦠',cls:'necro',
  need:[{id:'plague',lv:3},{id:'lifedrain',lv:3}],
  desc:'Чумное облако III + Жатва душ III. Огромные зоны чумы и вытягивание жизни.'},
 {id:'archon',name:'Архонт',icon:'👑',cls:'arcane',
  need:[{id:'shield',lv:3},{id:'parm',lv:3,type:'passive'}],
  desc:'Чародейский барьер III + Каменная кожа III (пассивка). Золотые импульсы, броня +6.'},
];

const SYNERGIES=[
 {id:'firewind',name:'Огненный вихрь',icon:'🌪️',
  need:[{id:'fireball'},{id:'pspd',type:'passive'}],
  fx:{area:.25},desc:'+25% к области взрывов'},
 {id:'deadcircle',name:'Хоровод смерти',icon:'💀',
  need:[{id:'skeletons'},{id:'ring'}],
  fx:{ringSpd:.5,minionDmg:.15},desc:'+50% скорость вращения кольца и скелетов, +15% их урон'},
 {id:'ashrain',name:'Пепельный дождь',icon:'☄️',
  need:[{id:'meteor'},{id:'fireball'}],
  fx:{burn:.4},desc:'+40% сила поджога'},
 {id:'ionize',name:'Ионизация',icon:'⚡',
  need:[{id:'lightning'},{id:'ball'}],
  fx:{chains:1,dmg:.1},desc:'+1 цепь молнии, +10% общего урона'},
 {id:'bloodpact',name:'Кровавый контракт',icon:'🩸',
  need:[{id:'lifedrain'},{id:'deathburst'}],
  fx:{vamp:2},desc:'+2 HP за убийство (в рамках предела насыщения)'},
 {id:'abszero',name:'Абсолютный ноль',icon:'❄️',
  need:[{id:'icelance'},{id:'nova'}],
  fx:{dmg:.2,area:.15},desc:'+20% урона, +15% область'},
 {id:'phalanx',name:'Фаланга',icon:'🛡️',
  need:[{id:'shield'},{id:'skeletons'}],
  fx:{armor:1,skel:1},desc:'+1 броня, +1 скелет-страж'},
 {id:'miasma',name:'Миазмы',icon:'🧪',
  need:[{id:'aura'},{id:'plague'}],
  fx:{minionDmg:.2},desc:'+20% урон ауры и прислужников'},
 {id:'prismSyn',name:'Призма',icon:'🔷',
  need:[{id:'ray'},{id:'boomer'}],
  fx:{ringSpd:.25,dmg:.1},desc:'+25% скорость вращения лучей, +10% урона'},
 {id:'stormEye',name:'Око бури',icon:'🌪️',
  need:[{id:'cyclone'},{id:'lightning'}],
  fx:{dmg:.15,pull:.25},desc:'+15% урона, +25% притяжение вихрей'},
 {id:'legion',name:'Легион',icon:'👥',
  need:[{id:'mirror'},{id:'skeletons'}],
  fx:{minionDmg:.2},desc:'+20% урон двойников и прислужников'},
];