'use strict';
const COMBOS=[
 {id:'sunstorm',name:'Солнечная буря',icon:'&',cls:'pyro',need:[{id:'fireball',lv:4},{id:'ring',lv:3}],desc:'Шары+новы огня.'},
 {id:'soulreaper',name:'Жнец душ',icon:'†',cls:'necro',need:[{id:'soularrow',lv:4},{id:'deathburst',lv:3}],desc:'Косы душ+новы.'},
 {id:'blackdeath',name:'Чёрная смерть',icon:'%',cls:'necro',need:[{id:'plague',lv:3},{id:'lifedrain',lv:3}],desc:'Чума+вампиризм.'},
 {id:'skywrath',name:'Гнев небес',icon:'z',cls:'storm',need:[{id:'lightning',lv:4},{id:'storm',lv:3}],desc:'Цепи+гром.'},
 {id:'vortex',name:'Великий вихрь',icon:'Ø',cls:'storm',need:[{id:'cyclone',lv:4},{id:'ball',lv:3}],desc:'4 циклона с притяжением.'},
 {id:'singularity',name:'Сингулярность',icon:'O',cls:'arcane',need:[{id:'arcane',lv:4},{id:'nova',lv:3}],desc:'Чёрная дыра.'},
 {id:'icestorm',name:'Ледяной шторм',icon:'^',cls:'arcane',need:[{id:'icelance',lv:4},{id:'ball',lv:3}],desc:'Лёд+сферы.'},
 {id:'laserstorm',name:'Лазерный шторм',icon:'|',cls:'arcane',need:[{id:'ray',lv:4},{id:'mirror',lv:3}],desc:'Один гигантский луч.'},
 {id:'avatar',name:'Аватар',icon:'@',cls:'arcane',need:[{id:'mirror',lv:4},{id:'arcane',lv:3}],desc:'4 миража-стрелка.'},
 {id:'archon',name:'Архонт',icon:'#',cls:'arcane',need:[{id:'shield',lv:3},{id:'parm',lv:3,type:'passive'}],desc:'Импульсы+броня.'},
 {id:'hellfire',name:'Пекло',icon:'#',cls:null,need:[{id:'incineration',lv:3},{id:'meteor',lv:2}],desc:'Кольцо взрывов.'},
 {id:'etherblaze',name:'Эфирный пожар',icon:'∆',cls:null,need:[{id:'blizzard',lv:3},{id:'fireball',lv:4}],desc:'Лёд→огонь.'},
 {id:'astrape',name:'Кара небес',icon:'z',cls:null,need:[{id:'storm',lv:3},{id:'meteor',lv:2}],desc:'Метеор+цепи.'},
 {id:'phoenix',name:'Феникс',icon:'v',cls:null,need:[{id:'tsunami',lv:3},{id:'blizzard',lv:2}],desc:'Волна+огонь.'},
 {id:'archmind',name:'Архиразум',icon:'O',cls:'arcane',need:[{id:'laserstorm',lv:1},{id:'singularity',lv:1}],desc:'ТИР2: луч+дыры.'},
 {id:'stormlord',name:'Владыка бури',icon:'z',cls:'storm',need:[{id:'vortex',lv:1},{id:'skywrath',lv:1}],desc:'ТИР2: циклоны+цепи.'},
 {id:'sunlord',name:'Солнечная корона',icon:'*',cls:'pyro',need:[{id:'sunstorm',lv:1},{id:'hellfire',lv:1}],desc:'ТИР2: корона огня.'},
 {id:'lich',name:'Лич',icon:'†',cls:'necro',need:[{id:'soulreaper',lv:1},{id:'blackdeath',lv:1}],desc:'ТИР2: косы+чума.'}];
const SYNERGIES=[
 {id:'firewind',name:'Огненный вихрь',icon:'~',need:[{id:'fireball'},{id:'pspd',type:'passive'}],fx:{area:.25},desc:'+25% область'},
 {id:'deadcircle',name:'Хоровод смерти',icon:'o',need:[{id:'skeletons'},{id:'ring'}],fx:{ringSpd:.5,minionDmg:.15},desc:'+вращение,+урон'},
 {id:'ashrain',name:'Пепельный дождь',icon:'v',need:[{id:'meteor'},{id:'fireball'}],fx:{burn:.4},desc:'+поджог'},
 {id:'ionize',name:'Ионизация',icon:'z',need:[{id:'lightning'},{id:'ball'}],fx:{chains:1,dmg:.1},desc:'+цепь,+урон'},
 {id:'bloodpact',name:'Кровавый контракт',icon:'&',need:[{id:'lifedrain'},{id:'deathburst'}],fx:{vamp:2},desc:'+вамп'},
 {id:'abszero',name:'Абсолютный ноль',icon:'^',need:[{id:'icelance'},{id:'nova'}],fx:{dmg:.2,area:.15},desc:'+урон,+область'},
 {id:'phalanx',name:'Фаланга',icon:'#',need:[{id:'shield'},{id:'skeletons'}],fx:{armor:1,skel:1},desc:'+броня,+скелет'},
 {id:'miasma',name:'Миазмы',icon:'∴',need:[{id:'aura'},{id:'plague'}],fx:{minionDmg:.2},desc:'+аура'},
 {id:'prismSyn',name:'Призма',icon:'|',need:[{id:'ray'},{id:'boomer'}],fx:{ringSpd:.25,dmg:.1},desc:'+лучи'},
 {id:'stormEye',name:'Око бури',icon:'Ø',need:[{id:'cyclone'},{id:'lightning'}],fx:{dmg:.15,pull:.25},desc:'+вихри'},
 {id:'legion',name:'Легион',icon:'@',need:[{id:'mirror'},{id:'skeletons'}],fx:{minionDmg:.2},desc:'+миньоны'},
 {id:'elemchaos',name:'Стихийный хаос',icon:'∆',need:[{id:'incineration'},{id:'blizzard'}],fx:{dmg:.15,burn:.25},desc:'+стихии'}];